### ISSUE TITLE
Первый todo сайта

### ISSUE THREAD

**Issue by sswwyyaatt** [ReDGamerR/redarmy#1]
### Make site great again

- [x] Пофиксить мобильную версию
- [x] Лёгкий редизайн
- [x] Добавить сайт в поиск
- [x] Вебхук от ArmaServer
- [x] Ссылка на сборку, отдельный отдел закачки.
- [x] Добавить F.A.Q
- [x] Так то  надо бы сделать почту и аккаунты, но зачем ?
- [x] Нехуй делать будет, донаты запилить.
- [x] Добавить changelog

**Comment by sswwyyaatt** [comment]
@ReDGamerR Помогай с мониторингом. Дизайн я напилю, с тебя вывод в web форме.

**Comment by sswwyyaatt** [comment]
Первый этап закончен
